model_type: protein_mpnn
checkpoint_protein_mpnn: ./model_params/proteinmpnn_v_48_020.pt
checkpoint_ligand_mpnn: ./model_params/ligandmpnn_v_32_010_25.pt
checkpoint_per_residue_label_membrane_mpnn: ./model_params/per_residue_label_membrane_mpnn_v_48_020.pt
checkpoint_global_label_membrane_mpnn: ./model_params/global_label_membrane_mpnn_v_48_020.pt
checkpoint_soluble_mpnn: ./model_params/solublempnn_v_48_020.pt

fasta_seq_separation: ":"
verbose: 1
pdb_path: ""
pdb_path_multi: ""
fixed_residues: ""
fixed_residues_multi: ""
redesigned_residues: ""
redesigned_residues_multi: ""
bias_AA: ""
bias_AA_per_residue: ""
bias_AA_per_residue_multi: ""
omit_AA: ""
omit_AA_per_residue: ""
omit_AA_per_residue_multi: ""
symmetry_residues: ""
symmetry_weights: ""
homo_oligomer: 0
out_folder: /home/out/
file_ending: ""
zero_indexed: 0
seed: 0
batch_size: 1
number_of_batches: 1
temperature: 0.1
save_stats: 0
ligand_mpnn_use_atom_context: 1
ligand_mpnn_cutoff_for_score: 8.0
ligand_mpnn_use_side_chain_context: 0
chains_to_design: null
parse_these_chains_only: ""
transmembrane_buried: ""
transmembrane_interface: ""
global_transmembrane_label: 0
parse_atoms_with_zero_occupancy: 0